# Generated by Django 4.2.16 on 2024-11-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='weeday',
            new_name='weekday',
        ),
    ]
