# Generated by Django 4.2.16 on 2024-11-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab', '0002_rename_weeday_timetable_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clas',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('view_clas', 'Can view clas'),)},
        ),
    ]
